name: Peiso Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node
        with:
          node-version: 14.21.3
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."




